### ISSUE TITLE
PYNQ Support

### ISSUE THREAD

**Issue by matanasban** [Xilinx/PYNQ_Composable_Pipeline#128]
Hey , just wondering , while trying to Overlay a bitfile of my project i get a hwh_parser error.
If im using an image with pynq which was created using the 2020.2 BSP , and i create my project bitfile and hwh file in vivado 2021.1 or 2022.2 versions , would it make sense that i get those hwh_parser errors? is it relevant if the versions of the bsp files and vivado are different?
Thanks !

**Comment by mariodruiz** [comment]
Hi @matanasban,

Is this a composable overlay design you are trying to download?
What parsing errors are you getting?

Mario

**Comment by matanasban** [comment]
Hey Mario , thanks for replaying.
Getting the following error : 
--> 244                 elif vlnv.split(':')[:2] == ['xilinx.com', 'module_ref']:
    245                     full_name += '/' + intf_id
    246 

AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mariodruiz** [comment]
Is this a composable overlay design you are trying to download?

What PYNQ version are you using?

**Comment by matanasban** [comment]
i honestly dont know how to verify if its composable or not , i've made a vivado project with alot of ips included , created a bitstream and tried to overlay it with (Overlay(bitfile.bit)) and it failed.
using 2020.2 PYNQ version as i described at the beginning

**Comment by mariodruiz** [comment]
If you do not know if it is a composable overlay, it means it is not. Therefore, this is not the appropriate place for support.

I suggest you post your question on the PYNQ forum https://discuss.pynq.io/
