### ISSUE TITLE
KV260 build overlay instructions and scripts

### ISSUE THREAD

**Issue by vmayoral** [Xilinx/PYNQ_Composable_Pipeline#46]
From the material published (videos, articles, etc.) it seems that KV260 is supported. Any chance to get an experience with KV260 similar to the one we have with [Pynq-Z2](https://github.com/Xilinx/PYNQ_Composable_Pipeline/tree/main/boards/Pynq-Z2)?

**Comment by mariodruiz** [comment]
That is coming in the next release `1.0.0` https://github.com/Xilinx/PYNQ_Composable_Pipeline/tree/v1.0.0/boards/KV260
