### ISSUE TITLE
Install error Pynq 2.7

### ISSUE THREAD

**Issue by SEHAIRIKamal** [Xilinx/PYNQ_Composable_Pipeline#58]
Trying to install Pynq-Composable_Pipeline on Pynq-Z1 with version 2.7
The command
`sudo pip3 install PYNQ_Composable_Pipeline/ --verbose`
returns the following. I checked Cython version, I have the 0.29.28 version but it says that the 0.29.14 is installed

```
Using pip 22.0.3 from /usr/local/share/pynq-venv/lib/python3.8/site-packages/pip (python 3.8)
Processing /PYNQ_Composable_Pipeline
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting pynq>=2.6.0
    Using cached pynq-2.7.0-cp38-cp38-linux_armv7l.whl
  Collecting graphviz>=0.16
    Using cached graphviz-0.19.1-py3-none-any.whl (46 kB)
  Collecting cffi
    Using cached cffi-1.15.0-cp38-cp38-linux_armv7l.whl
  Collecting numpy
    Using cached numpy-1.22.2.zip (11.4 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting pandas
    Using cached pandas-1.4.1.tar.gz (4.9 MB)
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [20 lines of output]
        Traceback (most recent call last):
          File "/tmp/tmpy1gn_yn6", line 363, in <module>
            main()
          File "/tmp/tmpy1gn_yn6", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/tmp/tmpy1gn_yn6", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
            return self._get_build_requires(
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 128, in _get_build_requires
            self.run_setup()
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 249, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 651, in <module>
            ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
          File "setup.py", line 411, in maybe_cythonize
            raise RuntimeError(
        RuntimeError: Cannot cythonize with old Cython version (0.29.14 installed, needs 0.29.24)
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/share/pynq-venv/bin/python3 /tmp/pip-standalone-pip-qdl2sgw8/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9z3z4h5y/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'pynq>=2.6.0' 'graphviz>=0.16'
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

```

**Comment by mariodruiz** [comment]
Hi,

Are you installing from the main branch? The main branch should be aligned with pynq 2.6.2.

I would suggest you install from the `v1.0.0-dev` branch, which is for pynq 2.7.0. This branch is very stable and almost ready for release.

**Comment by SEHAIRIKamal** [comment]
Hi Mario
python3 -m pip install PYNQ_Composable_Pipeline/ --no-build-isolation 
This instruction returns this error saying that Pynq-Z1 is not supported

`python3 -m pip install PYNQ_Composable_Pipeline/ --no-build-isolation
Processing ./PYNQ_Composable_Pipeline
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 236, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 120, in <module>
          check_env()
        File "setup.py", line 38, in check_env
          raise ValueError("Board {} is not supported.".format(board))
      ValueError: Board Pynq-Z1 is not supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by mariodruiz** [comment]
Yes, that's correct. Glad this works. It should be solved when the branch is merged in main.
